"""Versioned provider-independent contracts shared by both tracks."""

from app.contracts.actor import ActorContext, ActorKind, ParticipantRole
from app.contracts.ai import (
    AnalysisCarryDistanceCondition,
    AnalysisContentType,
    AnalysisFloorCondition,
    AnalysisRequest,
    AnalysisResult,
    AnalysisSourceContext,
    DraftItem,
    DraftLocationCondition,
)
from app.contracts.events import DomainEvent, DomainEventType
from app.contracts.maintenance import (
    BackgroundJobType,
    MediaDeletionOutcome,
    MediaDeletionResultV1,
    MediaDeletionTaskV1,
    MediaDeletionWorkV1,
    MediaValidationOutcome,
    MediaValidationResultV1,
    MediaValidationTaskV1,
    MediaValidationWorkV1,
)
from app.contracts.media import MediaAssetRef, MediaAssetStatus, MediaPurpose
from app.contracts.ports import (
    AIProviderPort,
    CachePort,
    EventBusPort,
    ObjectStoragePort,
    ProviderError,
    ProviderErrorKind,
    StorageObjectGeneration,
    StorageObjectMetadata,
    StoragePort,
    StorageUploadTarget,
    TaskQueuePort,
)
from app.contracts.primitives import (
    AggregateId,
    AnalysisRunId,
    BackgroundJobId,
    CaptureSessionId,
    EventId,
    IdempotencyKey,
    JobId,
    MediaAssetId,
    ParticipantId,
    RequestId,
    RoomZoneId,
    TraceId,
    utc_now,
)

__all__ = [
    "AIProviderPort",
    "ActorContext",
    "ActorKind",
    "AggregateId",
    "AnalysisCarryDistanceCondition",
    "AnalysisContentType",
    "AnalysisFloorCondition",
    "AnalysisRequest",
    "AnalysisResult",
    "AnalysisRunId",
    "AnalysisSourceContext",
    "BackgroundJobId",
    "BackgroundJobType",
    "CachePort",
    "CaptureSessionId",
    "DomainEvent",
    "DomainEventType",
    "DraftItem",
    "DraftLocationCondition",
    "EventBusPort",
    "EventId",
    "IdempotencyKey",
    "JobId",
    "MediaAssetId",
    "MediaAssetRef",
    "MediaAssetStatus",
    "MediaDeletionOutcome",
    "MediaDeletionResultV1",
    "MediaDeletionTaskV1",
    "MediaDeletionWorkV1",
    "MediaPurpose",
    "MediaValidationOutcome",
    "MediaValidationResultV1",
    "MediaValidationTaskV1",
    "MediaValidationWorkV1",
    "ObjectStoragePort",
    "ParticipantId",
    "ParticipantRole",
    "ProviderError",
    "ProviderErrorKind",
    "RequestId",
    "RoomZoneId",
    "StorageObjectGeneration",
    "StorageObjectMetadata",
    "StoragePort",
    "StorageUploadTarget",
    "TaskQueuePort",
    "TraceId",
    "utc_now",
]
